name: HTTPIE_HMAC Actions

on: push

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
  aws-test:
    runs-on: ubuntu-latest
    name: Test against AWS bucket
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Download a file from S3 using httpie-hmac
        env:
          HTTPIE_HMAC_SECRET: '${{ secrets.AWS_S3_TEST_SECRET }}'
          HTTPIE_HMAC_ACCESS_ID: '${{ secrets.AWS_S3_TEST_ACCESS }}'
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install .
          python3 -m httpie --check-status --auth-type=hmac --auth="format:aws4" GET https://api-testing-httpie-hmac.s3.eu-west-2.amazonaws.com/short.txt
  push:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
#     - name: Publish distribution 📦 to Test PyPI
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
#          repository-url: https://test.pypi.org/legacy/
      - name: Publish distribution 📦 to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
